// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://azyytewdncqvvfxwmdni.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImF6eXl0ZXdkbmNxdnZmeHdtZG5pIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM1NzE0NDYsImV4cCI6MjA2OTE0NzQ0Nn0.w48AAmNIbI-iwNbjo7NfK-W1jge2EOoVkXi87ORBb2E";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});